-- Party types reference table
CREATE TABLE party_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    icon VARCHAR(50),
    min_age INT,
    max_age INT,
    google_places_types VARCHAR(2000),
    search_keywords VARCHAR(4000),
    typical_duration VARCHAR(50),
    avg_cost_min INT,
    avg_cost_max INT,
    setting VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Search history table
CREATE TABLE searches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlation_id VARCHAR(255),
    age INT NOT NULL,
    party_types VARCHAR(1000),
    guest_count INT,
    budget_min INT,
    budget_max INT,
    zip_code VARCHAR(10),
    setting VARCHAR(20),
    max_distance_miles INT,
    venue_count INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Venue cache table
CREATE TABLE venues (
    google_place_id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(500) NOT NULL,
    address VARCHAR(1000),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    rating DOUBLE PRECISION,
    user_ratings_total INT,
    price_level INT,
    place_types VARCHAR(2000),
    phone_number VARCHAR(50),
    website VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Transactional outbox table
CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(255) NOT NULL,
    event_version INT DEFAULT 1,
    aggregate_type VARCHAR(255),
    aggregate_id VARCHAR(255),
    correlation_id VARCHAR(255),
    payload CLOB,
    published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP
);

-- ShedLock table
CREATE TABLE shedlock (
    name VARCHAR(64) PRIMARY KEY,
    lock_until TIMESTAMP NOT NULL,
    locked_at TIMESTAMP NOT NULL,
    locked_by VARCHAR(255) NOT NULL
);

-- Indexes
CREATE INDEX idx_searches_correlation_id ON searches(correlation_id);
CREATE INDEX idx_searches_zip_code ON searches(zip_code);
CREATE INDEX idx_searches_created_at ON searches(created_at);
CREATE INDEX idx_outbox_events_published_created ON outbox_events(published, created_at);
